/* Model class – CMM Coach Type Table
Developer – Anshul ,09/07/2020
*/

package com.mdms.mdms_coach.coachuncleansed.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity()
@Table(name="coach_data_cmm", schema="mdms_coach")
public class CoachDataCMM {
	
	@Column(name="coach_no")
	private String coachNo;
	
	@Id
	@Column(name="coach_id")
	private String coachId;
	
	@Column(name="coach_type")
	private String coachType;
	
	@Column(name="owning_rly")
	private String owningRly;
	

	@Column(name="base_depot")
	private String baseDepot;
	

	@Column(name="nominated_workshop")
	private String nominatedWorkshop;
	

	@Column(name="coach_category")
	private String coachCategory;
	

	@Column(name="gauge")
	private String gauge;
	
	
	@Column(name="fitness_type")
	private String fitnessType;
	

	@Column(name="coupling_type")
	private String couplingType;
	
	
	
@Column(name="brake_type")
private String brakeType;


@Column(name="power_generation_type")
private String powerGenerationType;
	
	@Column(name="tare_weight")
	private String tareweight;
	
	@Column(name="max_speed")
	private String maximumspeed;
	
	@Column(name="coach_age")
	private String coachage;
	

	@Column(name="coach_status")
	private String coachStatus;
	
	@Column(name="condemnation_date")
	private String condemnationDate;
	
	@Column(name="icms_coach_id")
	private String icmsCoachId;
	
	@Column(name="ac_flag")
	private String acFlag;
	
	@Column(name="built_date")
	private String builtDate;
	

	@Column(name="coach_commission_date")
	private String coachCommissionDate;
	
	@Column(name="coach_received_date")
	private String coachReceivedDate;
	
	
	@Column(name="manufacturer")
	private String manufacturer;
	

	@Column(name="underframe_no")
	private String underFrameNo;

	@Column(name="shell_no")
	private String shellNo;
	
	@Column(name="coach_auto_generated")
	private String coachAutoGenerated;
	
	@Column(name="is_biotoilet_fitted")
	private String isBiotoiletFitted;
	
	@Column(name="order_id")
	private String orderid;
	

	@Column(name="coach_owning_div")
	private String coachOwningDiv;
	

	@Column(name="factoryTurnoutDate")
	private String factoryTurnoutDate;
	

	@Column(name="rfid_status")
	private String rfidStatus;
	

	@Column(name="id")
	private Long Id;
	
	@Column(name="insert_or_update")
	private String insertOrUpdate;
	

	@Column(name="insert_or_update_date")
	private Date insertUpdateDate;
	
	
	@Column(name="added_by_import")
	private String addedByImport;


	public String getCoachNo() {
		return coachNo;
	}


	public void setCoachNo(String coachNo) {
		this.coachNo = coachNo;
	}


	public String getCoachId() {
		return coachId;
	}


	public void setCoachId(String coachId) {
		this.coachId = coachId;
	}


	public String getCoachType() {
		return coachType;
	}


	public void setCoachType(String coachType) {
		this.coachType = coachType;
	}


	public String getOwningRly() {
		return owningRly;
	}


	public void setOwningRly(String owningRly) {
		this.owningRly = owningRly;
	}


	public String getBaseDepot() {
		return baseDepot;
	}


	public void setBaseDepot(String baseDepot) {
		this.baseDepot = baseDepot;
	}


	public String getNominatedWorkshop() {
		return nominatedWorkshop;
	}


	public void setNominatedWorkshop(String nominatedWorkshop) {
		this.nominatedWorkshop = nominatedWorkshop;
	}


	public String getCoachCategory() {
		return coachCategory;
	}


	public void setCoachCategory(String coachCategory) {
		this.coachCategory = coachCategory;
	}


	public String getGauge() {
		return gauge;
	}


	public void setGauge(String gauge) {
		this.gauge = gauge;
	}


	public String getFitnessType() {
		return fitnessType;
	}


	public void setFitnessType(String fitnessType) {
		this.fitnessType = fitnessType;
	}


	public String getCouplingType() {
		return couplingType;
	}


	public void setCouplingType(String couplingType) {
		this.couplingType = couplingType;
	}


	public String getBrakeType() {
		return brakeType;
	}


	public void setBrakeType(String brakeType) {
		this.brakeType = brakeType;
	}


	public String getPowerGenerationType() {
		return powerGenerationType;
	}


	public void setPowerGenerationType(String powerGenerationType) {
		this.powerGenerationType = powerGenerationType;
	}


	public String getTareweight() {
		return tareweight;
	}


	public void setTareweight(String tareweight) {
		this.tareweight = tareweight;
	}


	public String getMaximumspeed() {
		return maximumspeed;
	}


	public void setMaximumspeed(String maximumspeed) {
		this.maximumspeed = maximumspeed;
	}


	public String getCoachage() {
		return coachage;
	}


	public void setCoachage(String coachage) {
		this.coachage = coachage;
	}


	public String getCoachStatus() {
		return coachStatus;
	}


	public void setCoachStatus(String coachStatus) {
		this.coachStatus = coachStatus;
	}


	public String getCondemnationDate() {
		return condemnationDate;
	}


	public void setCondemnationDate(String condemnationDate) {
		this.condemnationDate = condemnationDate;
	}


	public String getIcmsCoachId() {
		return icmsCoachId;
	}


	public void setIcmsCoachId(String icmsCoachId) {
		this.icmsCoachId = icmsCoachId;
	}


	public String getAcFlag() {
		return acFlag;
	}


	public void setAcFlag(String acFlag) {
		this.acFlag = acFlag;
	}


	public String getBuiltDate() {
		return builtDate;
	}


	public void setBuiltDate(String builtDate) {
		this.builtDate = builtDate;
	}


	public String getCoachCommissionDate() {
		return coachCommissionDate;
	}


	public void setCoachCommissionDate(String coachCommissionDate) {
		this.coachCommissionDate = coachCommissionDate;
	}


	public String getCoachReceivedDate() {
		return coachReceivedDate;
	}


	public void setCoachReceivedDate(String coachReceivedDate) {
		this.coachReceivedDate = coachReceivedDate;
	}


	public String getManufacturer() {
		return manufacturer;
	}


	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}


	public String getUnderFrameNo() {
		return underFrameNo;
	}


	public void setUnderFrameNo(String underFrameNo) {
		this.underFrameNo = underFrameNo;
	}


	public String getShellNo() {
		return shellNo;
	}


	public void setShellNo(String shellNo) {
		this.shellNo = shellNo;
	}


	public String getCoachAutoGenerated() {
		return coachAutoGenerated;
	}


	public void setCoachAutoGenerated(String coachAutoGenerated) {
		this.coachAutoGenerated = coachAutoGenerated;
	}


	public String getIsBiotoiletFitted() {
		return isBiotoiletFitted;
	}


	public void setIsBiotoiletFitted(String isBiotoiletFitted) {
		this.isBiotoiletFitted = isBiotoiletFitted;
	}


	public String getOrderid() {
		return orderid;
	}


	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}


	public String getCoachOwningDiv() {
		return coachOwningDiv;
	}


	public void setCoachOwningDiv(String coachOwningDiv) {
		this.coachOwningDiv = coachOwningDiv;
	}


	public String getFactoryTurnoutDate() {
		return factoryTurnoutDate;
	}


	public void setFactoryTurnoutDate(String factoryTurnoutDate) {
		this.factoryTurnoutDate = factoryTurnoutDate;
	}


	public String getRfidStatus() {
		return rfidStatus;
	}


	public void setRfidStatus(String rfidStatus) {
		this.rfidStatus = rfidStatus;
	}


	public Long getId() {
		return Id;
	}


	public void setId(Long id) {
		Id = id;
	}


	public String getInsertOrUpdate() {
		return insertOrUpdate;
	}


	public void setInsertOrUpdate(String insertOrUpdate) {
		this.insertOrUpdate = insertOrUpdate;
	}


	public Date getInsertUpdateDate() {
		return insertUpdateDate;
	}


	public void setInsertUpdateDate(Date insertUpdateDate) {
		this.insertUpdateDate = insertUpdateDate;
	}


	public String getAddedByImport() {
		return addedByImport;
	}


	public void setAddedByImport(String addedByImport) {
		this.addedByImport = addedByImport;
	}


	

	
}
